/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminFrame;

import main.startFrame;
import adminFrame.windowGetter.*;
import getters.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Just_Sample
 */
public class JAdminMainForm extends javax.swing.JFrame {

    /**
     * Creates new form JAdminMainForm
     */
    
    startFrame startFrame;
    
    public JAdminMainForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_admins = new javax.swing.JButton();
        btn_clients = new javax.swing.JButton();
        btn_rooms = new javax.swing.JButton();
        btn_EmpRoom = new javax.swing.JButton();
        btn_typeRooms = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin panel");

        btn_admins.setText("Админы");
        btn_admins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminsActionPerformed(evt);
            }
        });

        btn_clients.setText("Клиенты");
        btn_clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientsActionPerformed(evt);
            }
        });

        btn_rooms.setText("Комнаты");
        btn_rooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_roomsActionPerformed(evt);
            }
        });

        btn_EmpRoom.setText("Тип занятости комнат");
        btn_EmpRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpRoomActionPerformed(evt);
            }
        });

        btn_typeRooms.setText("Типы комнат");
        btn_typeRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_typeRoomsActionPerformed(evt);
            }
        });

        btn_exit.setText("Выйти");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_EmpRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_rooms, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(btn_admins, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_clients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_typeRooms, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_admins)
                    .addComponent(btn_clients))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_rooms)
                    .addComponent(btn_typeRooms))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_EmpRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(btn_exit)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        
        new startFrame().show();
        this.dispose();
        
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_adminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminsActionPerformed
        
        new AdminFrame().show();
        this.dispose();
        
    }//GEN-LAST:event_btn_adminsActionPerformed

    private void btn_clientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientsActionPerformed
        new AdminFrame(){

            List<Client> clientList = new ArrayList<>();
            
            @Override
            public void Init() {
                
                TitleFrame = "Clients control";
                columnName = new String[]{"Имя клиента"," Номер телефона", "Выбранная комната"};
                clientList = (List<Client>)new Client().getArrayObjects();
                objSQL = new Client();
                
            }

            @Override
            protected void rowInit(Object[] row, int i) {
                
                row[0] = clientList.get(i).getName();
                row[1] = clientList.get(i).getPhone();
                row[2] = clientList.get(i).getRoomNumber();
                
            }

            @Override
            protected void updateList() {
                
                System.out.println("RoomListUpdate");
                clientList = (List<Client>)new Client().getArrayObjects();
                countArray = clientList.size();
                
            }
            
        }.show();
        this.dispose();
    }//GEN-LAST:event_btn_clientsActionPerformed

    private void btn_roomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_roomsActionPerformed
        
        new AdminFrame(){

            List<Room> roomList = new ArrayList<>();
            
            @Override
            public void Init() {
                
                TitleFrame = "Room control";
                columnName = new String[]{"Номер комнаты"," тип комнаты", "Занятость комнаты"};
                roomList = (List<Room>)new Room().getArrayObjects();
                objSQL = new Room();
                
            }

            @Override
            protected void rowInit(Object[] row, int i) {
                
                row[0] = roomList.get(i).getRoomNumber();
                row[1] = roomList.get(i).getRoomType();
                row[2] = roomList.get(i).getRoomEmp();
                
            }

            @Override
            protected void updateList() {
                
                System.out.println("RoomListUpdate");
                roomList = (List<Room>)new Room().getArrayObjects();
                countArray = roomList.size();
                
            }

        }.show();
        this.dispose();
        
    }//GEN-LAST:event_btn_roomsActionPerformed

    //
    private void btn_typeRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_typeRoomsActionPerformed
        
        new AdminFrame(){

            List<Room> roomList = new ArrayList<>();
            
            @Override
            public void Init() {
                
                TitleFrame = "Room control";
                columnName = new String[]{"Номер комнаты"," тип комнаты", "Занятость комнаты"};
                roomList = (List<Room>)new Room().getArrayObjects();
                objSQL = new Room();
                
            }

            @Override
            protected void rowInit(Object[] row, int i) {
                
                row[0] = roomList.get(i).getRoomNumber();
                row[1] = roomList.get(i).getRoomType();
                row[2] = roomList.get(i).getRoomEmp();
                
            }

            @Override
            protected void updateList() {
                
                System.out.println("RoomListUpdate");
                roomList = (List<Room>)new Room().getArrayObjects();
                countArray = roomList.size();
                
            }

        }.show();
        this.dispose();
        
    }//GEN-LAST:event_btn_typeRoomsActionPerformed

    //Типы комнат
    private void btn_EmpRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EmpRoomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAdminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAdminMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EmpRoom;
    private javax.swing.JButton btn_admins;
    private javax.swing.JButton btn_clients;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_rooms;
    private javax.swing.JButton btn_typeRooms;
    // End of variables declaration//GEN-END:variables
}
